### PR TITLE
chore(release): version bump to 0.0.6

### PR DESCRIPTION
**Pull request by urbanisierung**
**What did I change?**

* Version bump to `0.0.6`
* Update changelog

**Why did I change it?**

* Last release workflow failed because of version conflict.

### CODE REVIEW

**Comment by urbanisierung** [comment]
@goenning Here's the PR as [discussed](https://github.com/goenning/google-indexing-script/pull/53#issuecomment-2112864100). Your last push was to version `0.1.0`. I bumped it to `0.0.6` - what do you prefer?

**Comment by goenning** [comment]
Still not working.. @AntoineKM any idea what's wrong or some pointers on what I could try? 

Here's the error https://github.com/goenning/google-indexing-script/actions/runs/9109233595

**Comment by antoinekm** [comment]
Hey @goenning it fail because the version was changed manually, you should add the changes with `npm run changeset` and check if the changeset is valid with the [changeset-bot](https://github.com/changesets/bot)

**Comment by antoinekm** [comment]
I will fix it in a PR

**Comment by goenning** [comment]
@urbanisierung should be good now, thanks again @AntoineKM

**Comment by urbanisierung** [comment]
Supernice, thank you both!

**Pull request merged**
