### PR TITLE
fix changes

### PR DESCRIPTION
**Pull request by antoinekm**
**What did I change?**
I fixed the issue related to version/changes. I've also added some information so that new contributors don't get confused.

**Why did I change it?**
Changeset couldn't find a non-existent version.

### CODE REVIEW

**Comment by antoinekm** [comment]
@goenning once you merge, it will create a new pull request through the changeset bot to publish the version :D

**Comment by goenning** [comment]
So basically every PR must have a changeset file?

**Comment by antoinekm** [comment]
> So basically every PR must have a changeset file?

Yes, or you have to do it yourself.

This again fails but for another problem this time, I think it's related to the NPM_TOKEN, could you check if it's still the right one in the repo settings > Secrets and variables > Actions > NPM_TOKEN?

**Comment by goenning** [comment]
The token had expired. The one is valid for much longer, i'll be dead before it expires :D

Thanks @AntoineKM it's working again

**Pull request merged**
