### PR TITLE
Add cli

### LINKED ISSUE #22: Publish as npm package
First of all: Thank you very much for this great project! 

I would love to just install it globally via `npm install` and then use it as a CLI. Do you plan to release this script as an npm package?

### PR DESCRIPTION
**Pull request by antoinekm**
**What did I change?**
- [x] I exported all members.
- [x] I've adapted the main function to the use of a cli (`gis seogets.com` or `google-indexing-script seogets.com`) and external use (`index("seogets.com")`).
- [x] I've added the possibility of using environment variables or arguments to pass the client email, private key or path (for simple use, as in Github Actions, for example).
- [x] I've added changesets to make release notes.
- [x] I've added the documentation to `README.md` for users
- [x] I've added the documentation to `README.md` for future contributors

**Why did I change it?**
Close: #22
And enable more global use in different projects.

### CODE REVIEW

**Comment by goenning** [comment]
Looks good overall, the the README will become very long with this change.
I think we should only mention the recommended method (CLI), and maybe a link to alternatives installation methods which would be in a different fine, what you think?

I like the idea of having a `~/.gis` folder :+1:

I think it should be possible to pass the path to the json as an argument as well, the variants would be:
```
gis seogets --path /path/to
or
gis seogets --client-email abc@example.com --private-key PRIVATE KEYS
or 
GOOGLE_CLIENT_EMAIL=abc GOOGLE_PRIVATE_KEY=test gis seogest
```

**Comment by antoinekm** [comment]
> Looks good overall, the the README will become very long with this change. I think we should only mention the recommended method (CLI), and maybe a link to alternatives installation methods which would be in a different fine, what you think?
> 
> I like the idea of having a `~/.gis` folder 👍
> 
> I think it should be possible to pass the path to the json as an argument as well, the variants would be:
> 
> ```
> gis seogets --path /path/to
> or
> gis seogets --client-email abc@example.com --private-key PRIVATE KEYS
> or 
> GOOGLE_CLIENT_EMAIL=abc GOOGLE_PRIVATE_KEY=test gis seogest
> ```

I've added a few collapsed sections, made a few changes, after that, I'm not great at README / Documentation so if you want to make changes after the merge that would be welcome!

**Comment by antoinekm** [comment]
I've also added the option for a custom path!

**Comment by goenning** [comment]
Amazing work @AntoineKM 
LGTM 🚀

**Comment by antoinekm** [comment]
Thanks, that's it! I've even added a template for future pull requests, actions to check that the build doesn't fail. The only thing to do now is install this bot: https://github.com/changesets/bot and setup the secret variable `NPM_TOKEN` in the repo config!

**Comment by prokopsimek** [comment]
The `NPM_TOKEN` seems to be still missing so the package can't be published. https://github.com/goenning/google-indexing-script/actions/runs/8175267647/job/22351987709

Or is that caused that there is no tag in the repository yet?

Can't wait to use it such with one-line command `npx google-indexing-script example.com`! 🙌 

---------
As the owner of the SDK, you will need to set up secrets in your repository to store your npm token. Here are the steps to set up secrets:

1. Sign up on https://www.npmjs.com/, go to your “Account” > “Access Tokens”, and generate a new Classic Token with type Automation ([get more info here](https://docs.npmjs.com/creating-and-viewing-access-tokens)).
2. In your repository on GitHub, where you want to set the automation, go to "Settings" > "Secrets and variables" > “Actions” and click on the "New repository secret" button.
3. In the "Name" field, enter NPM_TOKEN.
4. In the "Secret" field, paste the token you just created on npmjs.com.
5. Click on the "Add secret" button to save your npm token as a secret.

Now your npm token is securely stored in your repository and can be accessed by your GitHub Action. When the GitHub Action runs, it will use the token to authenticate with the npm registry and publish your SDK.

Note that you should never share your npm token with anyone and avoid committing it to your codebase. By using secrets, you can ensure that your token is only accessible to authorized users and that it is not exposed in your code.

Source: https://www.dxheroes.io/blog/release-and-publish-a-new-javascript-sdk-version-automatically-a-step-by-step-guide

**Comment by goenning** [comment]
That's set up on the repo now, and the first version was released to NPM this morning

**Comment by antoinekm** [comment]
> That's set up on the repo now, and the first version was released to NPM this morning

Nice @goenning !

To prevent #35 failing, you also need to authorize this in the repo settings:
image

Then try to rerun the action and it should work 😁

**Comment by goenning** [comment]
Done! It's all green now!

**Comment by antoinekm** [comment]
@goenning I think the error keep happening due to this: https://stackoverflow.com/a/73155199/12379218

**Pull request merged**
