### PR TITLE
Add rate limit error handling

### LINKED ISSUE #8: 429 error
site has about 6 million web pages, and a 429 error occurs during batch processing.

### PR DESCRIPTION
**Pull request by antoinekm**
**What did I change?**
I've added a custom error message and a process stop when a 429 error occurs.

**Why did I change it?**
To partially fix #8, but as we discussed (https://github.com/goenning/google-indexing-script/issues/8#issuecomment-1961838102), we'll also need to add a progress backup in a future pull request.

### CODE REVIEW

**Comment by goenning** [comment]
There's already some sort of built-in progress backup using the `.cache` folder.

If there's a 429 before the .cache is saved, we save the url with status "Error" (or maybe "RateLimited"?), but we don't exit the script.

After the .cache is saved, when we're doing the indexing process, if there's a 429 we notify the user and exit cleanly instead of treating it as an error.

What you think?

**Comment by antoinekm** [comment]
Yes it can be good I'll try to do it like that

**Comment by antoinekm** [comment]
@goenning it might be better now what do you think ?

**Comment by antoinekm** [comment]
https://github.com/goenning/google-indexing-script/assets/54948363/6268b448-de02-4b6f-94da-3c974295cb69

**Comment by goenning** [comment]
Looks great, thank you! :)

**Pull request merged**
